### ISSUE TITLE
ContainerView on Veracity using Chrome

### ISSUE THREAD

**Issue by DNVTestMonkey** [veracity/veracity-documentation#46]
Issue exists under the following conditions:
Data manager of Veracity container
Using Chrome Browser

When trying to navigate to the content view in a data container on Veracity.com, presented with error redirect as pictured in attached file.
![container_viewchrome](https://user-images.githubusercontent.com/15673400/52292156-15b0cf00-2942-11e9-8424-9869723e3420.PNG)

**Comment by rudfoss** [comment]
Hello, this is a repository for the documentation files only. Technical issues should be reported through the normal support channles. See the "Support" section on veracity.com
